import assert from 'node:assert/strict';
import {trackEvent,trackScene,trackRoundComplete} from '../src/utils/analytics.js';
const calls=[];
globalThis.window={location:{hostname:'plug-run.io'},gtag:(...args)=>calls.push(args)};
assert.equal(trackEvent('test',{crew:'afterlight',account_id:'secret',house_number:NaN}),true);
assert.deepEqual(calls.pop(),['event','test',{analytics_version:'2',crew:'afterlight'}]);
const scene={runKind:'journey',role:'runner',blockGangID:'iron-row',blockIndex:3,pveRound:15};
trackRoundComplete('runner',15,true,scene);
assert.deepEqual(calls.pop()[2],{analytics_version:'2',game_mode:'campaign',player_role:'runner',crew:'iron-row',block_number:3,house_number:15,round_number:15,success:true});
assert.equal(trackScene({rivalRace:{recording:true}},'test'),false);
window.location.hostname='localhost';
assert.equal(trackEvent('test'),false);
window.PLUG_RUN_ANALYTICS_DEBUG=true;
assert.equal(trackEvent('test'),true);
assert.equal(calls.pop()[2].debug_mode,true);
window.gtag=()=>{throw Error('offline');};
assert.equal(trackEvent('test'),false);
delete globalThis.window;
assert.equal(trackEvent('test'),false);
console.log('analytics: all assertions passed');
